src/com/inbox/model/InboxService.java
package com.inbox.model;

import java.util.Comparator;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

import com.util.SortMailState;

public class InboxService {
	private InboxDAO_interface dao;
	
	public InboxService() {
		dao = new InboxDAO_JDBC();
	}
	
	public List<InboxVO> getAll(){
		return dao.selectAll();
	}
	
	public InboxVO getOne(String inbox_Mail_ID) {
		return dao.select(inbox_Mail_ID);
	}

	
//搜尋 會員的“收件夾”  state = "4"
//搜尋 會員的“寄件夾”  state = "1"
	public Set<InboxVO>getInboxByMemberID(String state, String member_ID){
		Set<InboxVO>mails = dao.selectByMember(member_ID);
		SortMailState mail = new SortMailState();

		return mail.sortMail(state, mails);
	}
//	public Set<InboxVO>getOutboxByMemberID(String state, String member_ID){
//		Set<InboxVO>mails = dao.selectByMember(member_ID);
////		mails.removeIf(inboxVO -> (!inboxVO.getInbox_Mail_State().equals("1")));
////		Iterator<InboxVO>iter = mails.iterator();
////		while(iter.hasNext()) {
////			if(!iter.next().getInbox_Mail_State().equals("2")) {
////				iter.remove();
////			}
////		}
////		System.out.println("iter:"+ iter);
////		System.out.println("iter:"+ mails);
//		
////		TreeSet<InboxVO> mailTree = new TreeSet<InboxVO>(new Comparator<InboxVO>() {
////
////			@Override
////			public int compare(InboxVO o1, InboxVO o2) {
////				return -o1.getInbox_Mail_TimeStamp().compareTo(o2.getInbox_Mail_TimeStamp());
////			}
////		});
////		mailTree.addAll(mails);
////		System.out.println("mailTree:" + mailTree);
//		SortMailState mail = new SortMailState();
//		return mail.sortMail(state, mails);
//	}
	
	public InboxVO writeMail(String member_ID, String emp_ID, String inbox_Mail_Info, String inbox_Mail_Title, String inbox_Mail_State) {
		if(member_ID != null && inbox_Mail_Info != null && inbox_Mail_Title != null) {
			InboxVO inbox = new InboxVO();
			
			inbox.setEmp_ID(emp_ID);
			inbox.setInbox_Mail_Info(inbox_Mail_Info);
			inbox.setMember_ID(member_ID);
			inbox.setInbox_Mail_Title(inbox_Mail_Title);
			inbox.setInbox_Mail_State(inbox_Mail_State);
			
			InboxVO inbox_insert = dao.insert(inbox);
			InboxVO inbox_duplicate = new InboxVO();
			Integer tmp = Integer.parseInt(inbox_Mail_State) + 1;
			inbox_duplicate.setEmp_ID(emp_ID);
			inbox_duplicate.setInbox_Mail_Info(inbox_Mail_Info);
			inbox_duplicate.setInbox_Mail_State(tmp.toString());
			inbox_duplicate.setInbox_Mail_Title(inbox_Mail_Title);
			inbox_duplicate.setMember_ID(member_ID);
			
			InboxVO inbox_duplicate_tmp = dao.insert(inbox_duplicate);
			return inbox_insert;
			
			
//			return inbox;
			
		}
		return null;
	}
	
	public Integer deleteMail(String inbox_Mail_ID) {
		if(inbox_Mail_ID != null) {
			
			return dao.delete(inbox_Mail_ID);
		}
		return null;
	}
	
	public Set<InboxVO>getInboxByMemberID(String state, String member_ID, Map<String, String[]>map){
		Set<InboxVO>mails = dao.selectByMember(member_ID, map);
		SortMailState mail = new SortMailState();
		return mail.sortMail(state, mails);

	}
	
	public static void main(String[] args) {
		InboxService dao = new InboxService();
//		System.out.println(dao.getOne("IMID000000"));
//		System.out.println(dao.getAll());
		
//		InboxVO inbox = new InboxVO();
//		inbox.setEmp_ID("EID000001");
//		inbox.setInbox_Mail_Info("這是測試這是測試這是測試這是測試這是測試這是測試這是測試這是測試這是測試這是測試這是測試這是測試這是測試這是測試這是測試這是測試這是測試");
//		inbox.setMember_ID("MID000000");
//		inbox.setInbox_Mail_Title("test");
//		inbox.setInbox_Mail_State("1");
//		System.out.println(dao.writeMail(inbox.getMember_ID(), inbox.getEmp_ID(), inbox.getInbox_Mail_Info(), inbox.getInbox_Mail_Title(), inbox.getInbox_Mail_State()));
		
		
//		inbox.setInbox_Mail_ID("5");
//	    inbox.setEmp_ID("1000");
//		inbox.setMember_ID("5");
//		inbox.setInbox_Mail_Info("update test");
//		dao.update(inbox);
		
//		System.out.println(dao.deleteMail("IMID000010"));
		
//		System.out.println(dao.getInboxByMemberID("MID000000"));
//		System.out.println(dao.getOutboxByMemberID("1", "MID000000"));
		
	}
	
}

src/com/member/controller/MemberUpdateController.java
package com.member.controller;

import java.io.IOException;
import java.io.InputStream;
import java.io.UnsupportedEncodingException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.servlet.http.Part;

import com.member.model.MemberService;
import com.member.model.MemberVO;

@WebServlet("/member/MemberUpdate.Controller")
@MultipartConfig(fileSizeThreshold = 1024 * 1024, maxFileSize = 5 * 1024 * 1024, maxRequestSize = 5 * 5 * 1024 * 1024)
public class MemberUpdateController extends HttpServlet {
	private static final long serialVersionUID = 1L;
       


	protected void doGet(HttpServletRequest request, HttpServletResponse response)  {
		try {
			request.setCharacterEncoding("UTF-8");
		} catch (UnsupportedEncodingException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		String action = request.getParameter("action");
		
		if ("Update".equals(action)) {
			Map<String, String> errorMsgs = new HashMap<String, String>();
			request.setAttribute("errorMsg", errorMsgs);
			

//			System.out.println(member_Est_Time);
//			System.out.println(member_ID);
//			System.out.println(member_Name);
//			System.out.println(member_Account);
//			System.out.println(member_Pwd);
//			System.out.println(member_Sex);
//			System.out.println(member_Mail);
//			System.out.println(member_AddressMain);
//			System.out.println(member_AddressDetail);
//			System.out.println(member_BirthString_Stirng);
//			System.out.println(member_Img);
			try {
//接收參數
				java.util.Date today = new java.util.Date();
				java.sql.Date member_Est_Time = new java.sql.Date(today.getTime());
				Integer member_State = new Integer(1);
				String member_ID = request.getParameter("id").trim();
				String member_Name = request.getParameter("name").trim();
				String member_Account = request.getParameter("account").trim();
				String member_Pwd = request.getParameter("password").trim();
				String member_Sex = request.getParameter("sex").trim();
				String member_Phone = request.getParameter("phone").trim();
				String member_Mail = request.getParameter("email").trim();
				String member_AddressMain = request.getParameter("address_main").trim();
				String member_AddressDetail = request.getParameter("address_detail").trim();
				String member_Address = null;
				String member_Birth_String = request.getParameter("birthday").trim();
				java.sql.Date member_Birth = null;
				
				byte[] member_Img = null;
				
				try {
					Part part = request.getPart("img");
					System.out.println("part SIZE:" + part.getSize());
						if(part.getSize() == 0) {
							MemberService service = new MemberService();
							MemberVO member = service.getOne(member_ID);
							member_Img = member.getMember_Img();
						}else {
							InputStream in = part.getInputStream();
							member_Img = new byte[in.available()];
							in.read(member_Img);
							in.close();	
						}
						
				} catch (IOException e) {
					e.printStackTrace();
				}
//Name
				String member_NameReg = "^[(\u4e00-\u9fa5)(a-zA-Z0-9_)]{2,10}$";
				if(member_Name == null || member_Name.trim().length() == 0) {
					errorMsgs.put("name_empty", "Please input your Name");
				}
				else if(!member_Name.matches(member_NameReg)) {
					errorMsgs.put("name_Reg", "姓名格式錯誤");
				}
				
//Account		
				
				if(member_Account == null || member_Account.trim().length() == 0) {
					errorMsgs.put("account_empty", "Please input your account");
				}
//Password
				if(member_Pwd == null || member_Pwd.trim().length() == 0) {
					errorMsgs.put("password_empty", "Please input your password");
				}
//Phone			
				if(member_Phone == null || member_Phone.trim().length() == 0) {
					errorMsgs.put("phone_empty", "Please input your phone");
				}
//mail
				if(member_Mail == null || member_Mail.trim().length() == 0) {
					errorMsgs.put("mail_empty", "Please input your Email");
				}
//address
				if(member_AddressDetail == null || member_AddressDetail.trim().length() == 0) {
					errorMsgs.put("addressDetail_empty", "Please input your Address");
				}else {
					member_Address = member_AddressMain + member_AddressDetail;
				}
//sex
				if(member_Sex == null || member_Sex.trim().length() == 0) {
					errorMsgs.put("sex_empty", "Please choose your sex");
				}
//Birthday
				if(member_Birth_String == null || member_Birth_String.trim().length() == 0) {
					errorMsgs.put("birthday_empty", "Please input your birthday");
				}else {
					DateFormat format = new SimpleDateFormat("yyyy/MM/dd");
					java.util.Date utilDate = new java.util.Date();
					utilDate = format.parse(member_Birth_String);
					member_Birth = new java.sql.Date(utilDate.getTime());
					
				}
//				System.out.println(member_Address + member_Birth);
				
			
				MemberVO member = new MemberVO();
				member.setMember_ID(member_ID);
				member.setMember_Name(member_Name);
				member.setMember_Account(member_Account);
				member.setMember_Pwd(member_Pwd);
				member.setMember_Phone(member_Phone);
				member.setMember_Mail(member_Mail);
				member.setMember_Address(member_Address);
				member.setMember_Sex(member_Sex);
				member.setMember_Birth(member_Birth);
				
				if(!errorMsgs.isEmpty()) {
					request.setAttribute("member", member);
					RequestDispatcher failureView = request.getRequestDispatcher("/frontstage_member/MemberUpdate.jsp");
					failureView.forward(request, response);
					return;
				}
				
				
				MemberService service = new MemberService();
				MemberVO memberUpdate = service.update(member_ID, member_Account, member_Pwd, member_Name, member_Phone, member_Sex, member_Birth, member_Mail, member_Address, member_Img, member_Est_Time, member_State);
				System.out.println(memberUpdate);
				HttpSession session = request.getSession();
				session.setAttribute("member", memberUpdate);
//				RequestDispatcher successView = request.getRequestDispatcher("/listAllMember.jsp");
//				successView.forward(request, response);
				response.sendRedirect(request.getContextPath() + "/index.jsp");
			
			}catch (Exception e) {
				errorMsgs.put("other", "cant get message" + e.getMessage());
				try {
					request.getRequestDispatcher("/frontstage_member/MemberUpdate.jsp").forward(request, response);
				} catch (ServletException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
			
		}
	}


	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}

}

WebContent/frontstage_member/listAllMember.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="java.util.*"%>
<%@ page import="com.member.model.*"%>
<!DOCTYPE html>

<%-- <% 
	MemberService service = new MemberService();
	List<MemberVO> members = service.getAll();
	pageContext.setAttribute("members", members);
%> --%>
<jsp:useBean id="members" scope="page"
	class="com.member.model.MemberService" />
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport"
	content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel=stylesheet type="text/css"
	href="<%=request.getContextPath()%>/vendors/bootstrap/bootstrap.min.css">
<style type="text/css">
	div.pagination{
	  /* display: block; */
	  margin-top: 80px;
	  margin-bottom: 200px;
	  /* margin-left: 24%; */
	}
/* Pagination links */
	.pagination a {
	  color: black;
	  font-family: roboto;
	  font-size: 16px;
	  float: left;
	  padding-top: 4px;
	  text-decoration: none;
	  transition: background-color .3s;
	  margin-left: 2px;
	  margin-right: 2px;
	  border: 1px solid #E2E2E2;
	  border-radius: 4px;
	  height: 32px;
	  width: 32px;
	  box-sizing: border-box;
	  text-align: center;
	}
	
	/* Style the active/current link */
	.pagination a.active {
	  background-color: #E6903B;
	  color: white;
	}
	
	/* Add a grey background color on mouse-over */
	.pagination a:hover:not(.active) {
	  background-color: #ddd;
	}
	
	/* table Height  */
	tr {
	   line-height: 25px;
	   min-height: 25px;
	   height: 25px;
	}
</style>
<title>Insert title here</title>
</head>
<body>
	<nav
		class="navbar navbar-expand navbar-light d-flex justify-content-start"
		style="background-color: #e3f2fd;">
		<a class="navbar-brand mr-auto" href="#"> <img
			src="<%=request.getContextPath()%>/img/david_img/logo.png" width="30" height="30"
			class="d-inline-block align-top" alt="tourism"> Tourism
		</a>
		<ul class="navbar-nav">
			<li class="nav-item"><a class="nav-link" href="#"><i
					class="fas fa-pen"></i>建立行程</a></li>
			<li class="nav-item"><a class="nav-link" href="#"><i
					class="fas fa-store"></i>商城</a></li>
			<li class="nav-item"><a class="nav-link" href="#"><i
					class="fas fa-shopping-cart"></i>購物車</a></li>
			<li class="nav-item"><a class="nav-link" href="#"><i
					class="fas fa-sign-in-alt"></i>會員中心</a></li>
			<li class="nav-item"><a class="nav-link" href="#"><i
					class="fas fa-user"></i>USER</a></li>
		</ul>
	</nav>
	<form method="post" action="<c:url value="/member/login.controller" />">
		<input type="text" name="account" placeholder="帳號" value="${account }"><span>${errorMsg.account }</span>
		<input type="password" name="password" placeholder="密碼"> <span>${errorMsg.password }</span>
		<div>${errorMsg.login }</div>
		<div>${errorMsg.other }</div>
		<input type="hidden" name="action" value="login"> 
		<input type="submit" value="login">

	</form>
	<h1>所有會員</h1>
<%-- 	<c:forEach var="members" items="${members.all}">
		<h3>ID:${members.member_ID}</h3>
		<h3>ACCOUNT:${members.member_Account}</h3>
		<h3>PWD:${members.member_Pwd }</h3>

	</c:forEach> --%>

	<c:if test="${not empty member}">
		<h4>
			<span>${member.member_Account}</span><br> <span>${member.member_Name}</span><br>
		</h4>
	</c:if>

	<table class="table table-hover">
		<thead>
			<tr>
				<th style="width: 5%" scope="col">#</th>
				<th style="width: 10%" scope="col">ID</th>
				<th style="width: 10%" scope="col">ACCOUNT</th>
				<th style="width: 10%" scope="col">PASSWORD</th>
				<th style="width: 20%" scope="col">地址</th>
				<th style="width: 10%" scope="col">生日</th>
				<th style="width: 10%" scope="col">電話</th>
				<th style="width: 10%" scope="col">信箱</th>
				<th style="width: 10%" scope="col">建立時間</th>
				<th style="width: 10%" scope="col">圖片</th>
			</tr>
		</thead>
		<tbody>
		<%@ include file="pages/page1.file" %> 
		<c:forEach var="members" items="${members.all}" varStatus="loop" begin="<%=pageIndex%>" end="<%=pageIndex+rowsPerPage-1%>">
			<c:url value="/MemberUpdate.jsp" var="path">
				<c:param name="id" value="${members.member_ID}" />
				<c:param name="account" value="${members.member_Account}" />
				<c:param name="password" value="${members.member_Pwd}" />
				<c:param name="address" value="${members.member_Address}" />
				<c:param name="birthday" value="${members.member_Birth}" />
			</c:url>
			<tr>
				<th scope="row"><a href="${path}">${loop.count }</a></th>
				<td>${members.member_ID}</td>
				<td>${members.member_Account}</td>
				<td>${members.member_Pwd}</td>
				<td>${members.member_Address}</td>
				<td>${members.member_Birth }</td>
				<td>${members.member_Phone }</td>
				<td>${members.member_Mail }</td>
				<td>${members.member_Est_Time }</td>
				<td><img class="img-fluid rounded mx-auto " src="<%=request.getContextPath()%>/member/ShowMemberImage?id=${members.member_ID}"></td>
				
			</tr>
		</c:forEach>
		</tbody>
	</table>
	<%@ include file="pages/page2.file"%>
	<script
		src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
	<script
		src="<%=request.getContextPath()%>/vendors/jquery/jquery-3.4.1.min.js"></script>
	<script
		src="<%=request.getContextPath()%>/vendors/bootstrap/bootstrap.min.js"></script>
	<script
		src="<%=request.getContextPath()%>/vendors/popper/popper.min.js"></script>
</body>
</html>